Repository intel/fpga-runtime-for-opencl, pull requests merged in 2022-03, with the labels that each got.

#89 Fix TSAN issues in thread support library
  lib/acl_threadsupport/test/acl_threadsupport_test.cpp
Labels: bug

#63 Add Thread Sanitizer CI/CD
  .github/workflows/tsan.yml
Labels: enhancement

#81 Add documentation for how OpenCL runtime manages buffers
  docs/buffers.md
Labels: documentation

#96 Fix download location of zlib archive
  scripts/install_zlib.ps1
Labels: bug

#94 Add cl_intel_unified_shared_memory to supported extensions
  src/acl_platform.cpp
Labels: enhancement
