Repository intel/fpga-runtime-for-opencl, pull requests merged in 2022-04, with the labels that each got.

#99 Document releasing the runtime
  RELEASE.md
Labels: documentation

#109 Print warning when kernel argument has multiple buffer_location attributes
  src/acl_auto_configure.cpp
Labels: bug

#110 Make auto-discovery error message handling more failsafe
  src/acl_auto_configure.cpp
Labels: bug

#108 Factor out functions for auto-discovery parsing
  src/acl_auto_configure.cpp
Labels: enhancement

#102 High level documentation for OpenCL Implementations
  docs/README.md
Labels: documentation
