Repository intel/fpga-runtime-for-opencl, pull requests merged in 2022-02, with the labels that each got.

#70 Document git identity setup
  CONTRIBUTING.md
Labels: documentation

#76 Add thread sanitizer option to cmake
  CMakeLists.txt
Labels: enhancement

#77 Remove unused variable to avoid compiler warning
  lib/acl_threadsupport/test/acl_threadsupport_test.cpp
  test/acl_mem_test.cpp
Labels: bug

#75 Upgrade to c++17 standard
  CMakeLists.txt
Labels: enhancement
