Repository intel/fpga-runtime-for-opencl, pull requests merged in 2022-05, with the labels that each got.

#114 l_copy_and_adjust_arguments_for_device: reduce scope of device-side buffer increment
  src/acl_kernel.cpp
Labels: enhancement

#115 invocation_wrapper: support non-POD types using placement new
  src/acl_context.cpp
Labels: bug

#128 doc: fix inaccessible links to MMD functions
  docs/buffers.md
Labels: documentation

#131 Added comments for pll_setting_t and pll_settings_str
  include/acl_pll.h
  src/acl_device.cpp
Labels: documentation

#139 Explicitly clear the CSR_done bit
  src/acl_kernel_if.cpp
Labels: enhancement
